[build]
  command = "npm run build"
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/:splat" # IMPORTANT: Replace with your deployed backend URL
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 